# Generated by Django 5.0.2 on 2026-03-01 20:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import profiles.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Certificate Name')),
                ('issuing_organization', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization')),
                ('learning_reflection', models.TextField(blank=True, null=True, verbose_name='Learning Reflection')),
                ('key_takeaways', models.CharField(blank=True, max_length=500, null=True, verbose_name='Key Takeaways')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certs/%Y/', verbose_name='Certificate File')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Date Issued')),
                ('certificate_link', models.URLField(blank=True, null=True, verbose_name='Credential URL')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True, verbose_name='Company Slug')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Company Name')),
                ('sector', models.CharField(db_index=True, max_length=100, verbose_name='Sector/Industry')),
                ('location', models.CharField(max_length=100, verbose_name='Headquarters Location')),
                ('operating_since', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('mission_stmt', models.TextField(blank=True, verbose_name='Mission Statement')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=profiles.models.company_cover_path)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=profiles.models.company_logo_path, verbose_name='Company Logo')),
                ('is_hiring', models.BooleanField(default=False)),
                ('looking_for', models.CharField(choices=[('BUILDING', 'Heads Down / Building'), ('FUNDRAISING', 'Seeking Investment'), ('HIRING', 'Aggressively Hiring'), ('PARTNERING', 'Seeking Co-Founders'), ('SALES', 'Seeking B2B Clients')], default='BUILDING', max_length=20, verbose_name='Current Company Objective')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=200)),
                ('degree_title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField()),
                ('verification_file', models.FileField(upload_to=profiles.models.expert_credential_path)),
                ('personal_reflection', models.TextField(blank=True, help_text='A personal reflection or description of what you learned and achieved with this credential.', null=True)),
                ('admin_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('REMOTE', 'Remote'), ('ON_SITE', 'On-Site'), ('HYBRID', 'Hybrid')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertHeadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Headline')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expert_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Identity Link')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Profile Slug')),
                ('location', models.CharField(db_index=True, max_length=100, verbose_name='HQ Location')),
                ('bio_narrative', models.TextField(blank=True, verbose_name='Deep Biography')),
                ('years_experience', models.PositiveSmallIntegerField(default=1, verbose_name='Seniority')),
                ('right_now', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(200, message='Your mission details must be at least 200 characters. Share more context to attract the right people!')], verbose_name='Current Focus')),
                ('current_search', models.CharField(blank=True, choices=[('INTERN', 'Looking for an Internship'), ('FUNDING', 'Looking for Funding'), ('STARTUP', 'Looking for a Startup Team'), ('PROJECT', 'Looking for a Project to join'), ('MINDSET', 'Looking to meet people with the same mindset'), ('LEARNING', 'Just focusing on Studying'), ('FULL_TIME', 'Looking for a Full-time Job'), ('PART_TIME', 'Looking for a Part-time Job')], db_index=True, default='LEARNING', max_length=20, null=True, verbose_name='Current Objective')),
                ('collaboration_status', models.CharField(choices=[('OPEN', '🟢 Open to Collaborate'), ('BUSY', '🟡 Deep Work (Slow Response)'), ('CLOSED', '🔴 Not Accepting Requests')], default='OPEN', max_length=20, verbose_name='Availability')),
                ('last_signal_update', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest update. Used to calculate signal decay.')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=profiles.models.expert_cv_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Artifact')),
                ('admin_rating', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Competence Score')),
            ],
            options={
                'verbose_name': 'Expert Profile',
                'verbose_name_plural': 'Expert Profiles',
            },
        ),
        migrations.CreateModel(
            name='ExpertProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Narrative Description')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExpertSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Tag')),
                ('description', models.TextField(blank=True, verbose_name='Context')),
                ('level', models.CharField(choices=[('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('MASTER', 'Master')], max_length=20)),
                ('admin_status', models.CharField(db_index=True, default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Expert Skill',
            },
        ),
        migrations.CreateModel(
            name='ExpertThought',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(verbose_name='Markdown Body')),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FounderProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('mission_stmt', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='founder_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Profile Slug')),
                ('right_now', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(200, message='Your mission details must be at least 200 characters. Share more context to attract the right people!')], verbose_name='Current Focus')),
                ('current_search', models.CharField(blank=True, choices=[('INTERN', 'Looking for an Internship'), ('FUNDING', 'Looking for Funding'), ('STARTUP', 'Looking for a Startup Team'), ('PROJECT', 'Looking for a Project to join'), ('MINDSET', 'Looking to meet people with the same mindset'), ('LEARNING', 'Just focusing on Studying'), ('FULL_TIME', 'Looking for a Full-time Job'), ('PART_TIME', 'Looking for a Part-time Job')], db_index=True, default='LEARNING', max_length=20, null=True, verbose_name='Current Objective')),
                ('collaboration_status', models.CharField(choices=[('OPEN', '🟢 Open to Collaborate'), ('BUSY', '🟡 Deep Work (Slow Response)'), ('CLOSED', '🔴 Not Accepting Requests')], default='OPEN', max_length=20, verbose_name='Availability')),
                ('last_signal_update', models.DateTimeField(auto_now=True, help_text='Timestamp of the latest update. Used to calculate signal decay.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrowthLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(choices=[('LEARNING', 'Study/Learning'), ('WORK', 'Project Work'), ('LIFE', 'Personal/Habits')], db_index=True, default='LEARNING', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('narrative', models.TextField()),
                ('daily_photo', models.ImageField(blank=True, null=True, upload_to='growth_logs/%Y/%m/', verbose_name='Proof of Work')),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Growth Log',
                'verbose_name_plural': 'Growth Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_title', models.CharField(max_length=100)),
                ('work_arrangement', models.CharField(max_length=50)),
                ('commitment_type', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Preference Narrative')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('learning_motivation', models.TextField(blank=True, verbose_name='The Why')),
                ('progress_bar', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress %')),
                ('status', models.CharField(choices=[('INTERESTED', 'Interested'), ('LEARNING', 'Learning'), ('MASTERED', 'Mastered')], db_index=True, default='INTERESTED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='companies/news/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Project Title')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='Problem Statement')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='My Solution')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Live Link / GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=profiles.models.portfolio_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='projects/')),
                ('caption', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='companies/services/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VisionaryProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visionary_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Profile URL Slug')),
                ('institution', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Institution / School')),
                ('current_title', models.CharField(blank=True, max_length=100, null=True)),
                ('field_of_interest', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Primary Interest')),
                ('location', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Location')),
                ('bio_narrative', models.TextField(blank=True, verbose_name='Long-term Goal')),
                ('headline', models.CharField(blank=True, max_length=150, null=True, verbose_name='Professional Headline')),
                ('right_now', models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(200, message='Your mission details must be at least 200 characters. Share more context to attract the right people!')], verbose_name='Current Focus')),
                ('current_search', models.CharField(blank=True, choices=[('INTERN', 'Looking for an Internship'), ('FUNDING', 'Looking for Funding'), ('STARTUP', 'Looking for a Startup Team'), ('PROJECT', 'Looking for a Project to join'), ('MINDSET', 'Looking to meet people with the same mindset'), ('LEARNING', 'Just focusing on Studying'), ('FULL_TIME', 'Looking for a Full-time Job'), ('PART_TIME', 'Looking for a Part-time Job')], db_index=True, default='LEARNING', max_length=20, null=True, verbose_name='Current Objective')),
                ('collaboration_status', models.CharField(choices=[('OPEN', '🟢 Open to Collaborate'), ('BUSY', '🟡 Deep Work (Slow Response)'), ('CLOSED', '🔴 Not Accepting Requests')], default='OPEN', max_length=20, verbose_name='Availability')),
                ('last_signal_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_rating', models.PositiveSmallIntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Admin Rating')),
            ],
            options={
                'verbose_name': 'Visionary Profile',
                'verbose_name_plural': 'Visionary Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisionBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(verbose_name='Essay Content')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContactMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='profiles.company')),
            ],
            options={
                'verbose_name': 'Company Contact',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner / Primary Contact'), ('ADMIN', 'Administrator'), ('EDITOR', 'Content Editor'), ('ALUMNI', 'Past Member (No Access)')], default='ADMIN', max_length=15)),
                ('job_title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='profiles.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-role', 'user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='profiles.company')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyNews',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Article Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Short Summary')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='companies/news/covers/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('published_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='profiles.company')),
            ],
            options={
                'verbose_name': 'Company News',
                'verbose_name_plural': 'Company News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Deep Explanation')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='profiles.company')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySocialLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='profiles.company')),
            ],
            options={
                'verbose_name': 'Company Social Link',
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='expertprofile',
            constraint=models.CheckConstraint(check=models.Q(('admin_rating__gte', 0), ('admin_rating__lte', 5)), name='expert_rating_range_check'),
        ),
        migrations.AddField(
            model_name='expertheadline',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headlines', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertcredential',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertproject',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='expertthought',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_preferences', to='profiles.expertprofile'),
        ),
        migrations.AddField(
            model_name='newsgalleryimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='profiles.companynews'),
        ),
        migrations.AddField(
            model_name='projectgalleryimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='profiles.expertproject'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='profiles.project'),
        ),
        migrations.AddField(
            model_name='servicegalleryimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='profiles.companyservice'),
        ),
        migrations.AddConstraint(
            model_name='visionaryprofile',
            constraint=models.CheckConstraint(check=models.Q(('admin_rating__gte', 0), ('admin_rating__lte', 5)), name='visionary_rating_range_check'),
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profiles.visionaryprofile'),
        ),
        migrations.AddField(
            model_name='learningtarget',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_targets', to='profiles.visionaryprofile'),
        ),
        migrations.AddField(
            model_name='growthlog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_logs', to='profiles.visionaryprofile'),
        ),
        migrations.AddField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profiles.visionaryprofile'),
        ),
        migrations.AddField(
            model_name='visionblock',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_blocks', to='profiles.visionaryprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user')},
        ),
        migrations.AddConstraint(
            model_name='expertheadline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='unique_primary_headline_per_profile'),
        ),
        migrations.AddIndex(
            model_name='expertskill',
            index=models.Index(fields=['profile', 'admin_status'], name='skill_status_idx'),
        ),
    ]
