# Generated by Django 5.0.2 on 2026-03-06 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="founderprofile",
            name="admin_rating",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Admin Rating",
            ),
        ),
    ]
