# Generated by Django 5.0.2 on 2026-03-07 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_founderprofile_admin_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="last_signal_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp of the latest update. Used to calculate signal decay.",
            ),
        ),
        migrations.AlterField(
            model_name="founderprofile",
            name="last_signal_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp of the latest update. Used to calculate signal decay.",
            ),
        ),
    ]
