# Generated by Django 5.0.2 on 2026-03-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_alter_expertprofile_last_signal_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="collaboration_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open to Collaborate"),
                    ("BUSY", " Deep Work (Slow Response)"),
                    ("CLOSED", "Not Accepting Requests"),
                ],
                default="OPEN",
                max_length=20,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="founderprofile",
            name="collaboration_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open to Collaborate"),
                    ("BUSY", " Deep Work (Slow Response)"),
                    ("CLOSED", "Not Accepting Requests"),
                ],
                default="OPEN",
                max_length=20,
                verbose_name="Availability",
            ),
        ),
        migrations.AlterField(
            model_name="visionaryprofile",
            name="collaboration_status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open to Collaborate"),
                    ("BUSY", " Deep Work (Slow Response)"),
                    ("CLOSED", "Not Accepting Requests"),
                ],
                default="OPEN",
                max_length=20,
                verbose_name="Availability",
            ),
        ),
    ]
