# Generated by Django 5.0.2 on 2026-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_expertprofile_collaboration_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visionaryprofile",
            name="headline",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Professional Headline",
            ),
        ),
    ]
