# Generated by Django 5.0.2 on 2026-03-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_alter_visionaryprofile_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="is_rating_locked",
            field=models.BooleanField(
                default=False,
                help_text="Check this to stop the AI Oracle from auto-updating this rating.",
                verbose_name="Admin Rating Lock",
            ),
        ),
        migrations.AddField(
            model_name="founderprofile",
            name="is_rating_locked",
            field=models.BooleanField(
                default=False,
                help_text="Check this to stop the AI Oracle from auto-updating this rating.",
                verbose_name="Admin Rating Lock",
            ),
        ),
        migrations.AddField(
            model_name="visionaryprofile",
            name="is_rating_locked",
            field=models.BooleanField(
                default=False,
                help_text="Check this to stop the AI Oracle from auto-updating this rating.",
                verbose_name="Admin Rating Lock",
            ),
        ),
    ]
