# Generated by Django 5.0.2 on 2026-03-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="looking_for",
            field=models.CharField(
                choices=[
                    ("Expanding", "Expanding"),
                    ("FUNDRAISING", "Seeking Investment"),
                    ("HIRING", "Hiring"),
                    ("PARTNERING", "Seeking Co-Founders"),
                    ("SALES", "Seeking B2B Clients"),
                ],
                default="Expanding",
                max_length=20,
                verbose_name="Current Company Objective",
            ),
        ),
    ]
