# Generated by Django 5.0.2 on 2026-03-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_company_looking_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this expert to the top of the Nexus Feed.",
                verbose_name="Admin Selected",
            ),
        ),
        migrations.AddField(
            model_name="founderprofile",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this founder to the top of the Nexus Feed.",
                verbose_name="Admin Selected",
            ),
        ),
        migrations.AddField(
            model_name="visionaryprofile",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this visionary to the top of the Nexus Feed.",
                verbose_name="Admin Selected",
            ),
        ),
    ]
