# Generated by Django 5.0.2 on 2026-03-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0008_expertprofile_is_selected_founderprofile_is_selected_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertprofile",
            name="is_selected",
        ),
        migrations.RemoveField(
            model_name="founderprofile",
            name="is_selected",
        ),
        migrations.RemoveField(
            model_name="visionaryprofile",
            name="is_selected",
        ),
    ]
