# Generated by Django 5.0.2 on 2026-03-12 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_remove_expertprofile_is_selected_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertprofile",
            name="right_now",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        20,
                        message="Your mission details must be at least 200 characters. Share more context to attract the right people!",
                    )
                ],
                verbose_name="Current Focus",
            ),
        ),
        migrations.AlterField(
            model_name="visionaryprofile",
            name="right_now",
            field=models.TextField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        20,
                        message="Your mission details must be at least 200 characters. Share more context to attract the right people!",
                    )
                ],
                verbose_name="Current Focus",
            ),
        ),
    ]
