# Generated by Django 5.0.2 on 2026-04-06 08:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import profiles.models.user_profile
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_backfill_first_last_name"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("PRACTICE", "Learning / Bootcamp Project"),
                            ("REAL_WORLD", "Real-world / Client Project"),
                            ("STARTUP", "Startup / Own Company"),
                        ],
                        default="PRACTICE",
                        max_length=20,
                    ),
                ),
                ("role", models.CharField(blank=True, max_length=100)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                ("problem_statement", models.TextField(blank=True, null=True)),
                ("solution_narrative", models.TextField(blank=True, null=True)),
                (
                    "main_description",
                    models.TextField(blank=True, verbose_name="Main Description"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Live Link / GitHub"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectGallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=profiles.models.user_profile.project_image_path
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="profiles.portfolioproject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="portfolio",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Profile URL Slug",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Institution / School",
                    ),
                ),
                (
                    "field_of_interest",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Primary Interest",
                    ),
                ),
                (
                    "years_experience",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "bio_narrative",
                    models.TextField(
                        blank=True, verbose_name="Deep Biography / Long-term Goal"
                    ),
                ),
                (
                    "current_mission",
                    models.TextField(
                        blank=True,
                        help_text="What are you building or learning this exact month?",
                        max_length=1000,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(20)],
                        verbose_name="Current Focus (Right Now)",
                    ),
                ),
                (
                    "current_search",
                    models.CharField(
                        choices=[
                            ("INTERN", "Looking for an Internship"),
                            ("FUNDING", "Looking for Funding"),
                            ("STARTUP", "Looking for a Startup Team"),
                            ("PROJECT", "Looking for a Project to join"),
                            ("MINDSET", "Looking to meet people with the same mindset"),
                            ("LEARNING", "Just focusing on Studying"),
                            ("FULL_TIME", "Looking for a Full-time Job"),
                            ("PART_TIME", "Looking for a Part-time Job"),
                        ],
                        db_index=True,
                        default="LEARNING",
                        max_length=20,
                        verbose_name="Current Objective",
                    ),
                ),
                (
                    "collaboration_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open to Collaborate"),
                            ("BUSY", " Deep Work (Slow Response)"),
                            ("CLOSED", "Not Accepting Requests"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="Availability",
                    ),
                ),
                (
                    "admin_rating",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Platform Rating",
                    ),
                ),
                ("is_rating_locked", models.BooleanField(default=False)),
                (
                    "last_signal_update",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "cv_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.user_profile.profile_cv_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="Resume / CV PDF",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unified Profile",
                "verbose_name_plural": "Unified Profiles",
                "indexes": [
                    models.Index(
                        fields=["current_search", "-last_signal_update"],
                        name="profiles_us_current_658317_idx",
                    ),
                    models.Index(
                        fields=["collaboration_status"],
                        name="profiles_us_collabo_075eaa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnifiedJobPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role_title", models.CharField(max_length=100)),
                ("work_arrangement", models.CharField(max_length=50)),
                ("commitment_type", models.CharField(max_length=50)),
                ("description", models.TextField(verbose_name="Preference Narrative")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_preferences",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Skill Name"
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Why did you learn this? Or how do you use it?",
                        verbose_name="Context / Motivation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTERESTED", "Interested in learning"),
                            ("LEARNING", "Actively Learning"),
                            ("MASTERED", "Mastered / Using professionally"),
                        ],
                        default="LEARNING",
                        max_length=20,
                    ),
                ),
                (
                    "progress_bar",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("SENIOR", "Senior"),
                            ("MASTER", "Master"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("admin_status", models.CharField(default="PENDING", max_length=20)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-status", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProfileHeadline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Headline")),
                ("is_primary", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headlines",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "order"],
            },
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="profiles.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("DEGREE", "University Degree"),
                            ("CERTIFICATE", "Professional Certificate"),
                            ("COURSE", "Online Course / Bootcamp"),
                        ],
                        default="CERTIFICATE",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Degree / Certificate Name"
                    ),
                ),
                (
                    "issuer",
                    models.CharField(
                        max_length=200, verbose_name="Issuing Organization"
                    ),
                ),
                (
                    "reflection",
                    models.TextField(
                        blank=True, null=True, verbose_name="Personal Reflection"
                    ),
                ),
                (
                    "key_takeaways",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "file_upload",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.user_profile.credential_path,
                    ),
                ),
                (
                    "url_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Verification URL"
                    ),
                ),
                ("is_admin_verified", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ContentPost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("GROWTH_LOG", "Daily Growth Log"),
                            ("ESSAY", "Deep Thought / Essay"),
                            ("VISION_BLOCK", "Long-term Vision Statement"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. LEARNING, WORK, LIFE",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(verbose_name="Markdown Body")),
                (
                    "media_proof",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=profiles.models.user_profile.content_media_path,
                    ),
                ),
                ("visibility", models.CharField(default="PUBLIC", max_length=20)),
                ("is_verified", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_posts",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("role_title", models.CharField(max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("REMOTE", "Remote"),
                            ("ON_SITE", "On-Site"),
                            ("HYBRID", "Hybrid"),
                        ],
                        default="ON_SITE",
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveOpportunity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("MENTOR", "Seeking a Mentor"),
                            ("HACKATHON", "Weekend Project Partner"),
                            ("FREELANCE", "Available for Freelance"),
                            ("COFOUNDER", "Seeking Co-Founder"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Need a UI designer for a 48hr hackathon",
                        max_length=200,
                    ),
                ),
                ("details", models.TextField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_opportunities",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="profiles_li_is_acti_c4e7db_idx",
                    )
                ],
            },
        ),
    ]
