# Generated by Django 5.0.2 on 2026-04-06 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0013_portfolioproject_projectgallery_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpost",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="credential",
            name="url_link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Verification URL"
            ),
        ),
        migrations.AlterField(
            model_name="liveopportunity",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Live Link / GitHub"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="context",
            field=models.TextField(blank=True, verbose_name="Context / Motivation"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="current_mission",
            field=models.TextField(
                blank=True,
                help_text="What are you building or learning this exact month? (Migrated from 'right_now')",
                max_length=1000,
                null=True,
                validators=[django.core.validators.MinLengthValidator(20)],
                verbose_name="Current Focus (Right Now)",
            ),
        ),
    ]
