# Generated by Django 5.0.2 on 2026-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0014_alter_contentpost_category_alter_credential_url_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveopportunity",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
