# Generated by Django 5.0.2 on 2026-04-07 16:38

import profiles.models.new_unified_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0015_alter_liveopportunity_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentpost",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LEARNING", "Study/Learning"),
                    ("WORK", "Project Work"),
                    ("LIFE", "Personal/Habits"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentpost",
            name="media_proof",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.new_unified_profile.content_media_path,
                verbose_name="Proof of Work",
            ),
        ),
        migrations.AlterField(
            model_name="contentpost",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                max_length=20,
            ),
        ),
    ]
