# Generated by Django 5.0.2 on 2026-04-09 14:23

import django.db.models.deletion
import profiles.models.new_unified_profile
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_alter_contentpost_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RightNowPost",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_search",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTERN", "Looking for an Internship"),
                            ("FUNDING", "Looking for Funding"),
                            ("STARTUP", "Looking for a Startup Team"),
                            ("PROJECT", "Looking for a Project to join"),
                            ("MINDSET", "Looking to meet people with the same mindset"),
                            ("LEARNING", "Just focusing on Studying"),
                            ("FULL_TIME", "Looking for a Full-time Job"),
                            ("PART_TIME", "Looking for a Part-time Job"),
                        ],
                        db_index=True,
                        default="LEARNING",
                        max_length=20,
                        null=True,
                        verbose_name="Current Objective",
                    ),
                ),
                (
                    "collaboration_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OPEN", "Open to Collaborate"),
                            ("BUSY", " Deep Work (Slow Response)"),
                            ("CLOSED", "Not Accepting Requests"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        null=True,
                        verbose_name="Availability",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Headline / Milestone",
                    ),
                ),
                (
                    "body_narrative",
                    models.TextField(
                        blank=True, null=True, verbose_name="The Update (Markdown)"
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="External URL",
                    ),
                ),
                ("link_title", models.CharField(blank=True, max_length=255, null=True)),
                ("link_description", models.TextField(blank=True, null=True)),
                (
                    "link_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "link_domain",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Clicks on external_link"
                    ),
                ),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Show in Global Feed"
                    ),
                ),
                (
                    "is_active_focus",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If true, this is the current active status on their portfolio.",
                        verbose_name="Pinned to Profile Top",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_now_posts",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Right Now Post",
                "verbose_name_plural": "Right Now Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RightNowMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=profiles.models.new_unified_profile.right_now_media_path,
                        verbose_name="Gallery Image",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="profiles.rightnowpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Right Now Media",
                "verbose_name_plural": "Right Now Media",
                "ordering": ["order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="rightnowpost",
            index=models.Index(
                fields=["is_published", "-created_at"],
                name="profiles_ri_is_publ_c64110_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rightnowpost",
            index=models.Index(
                fields=["is_active_focus", "current_search"],
                name="profiles_ri_is_acti_5a150d_idx",
            ),
        ),
    ]
