# Generated by Django 5.0.2 on 2026-04-11 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_rightnowpost_rightnowmedia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RightNowComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "body",
                    models.TextField(max_length=1000, verbose_name="Comment Body"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="profiles.rightnowpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Right Now Comment",
                "verbose_name_plural": "Right Now Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RightNowLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="profiles.rightnowpost",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_posts",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Right Now Like",
                "verbose_name_plural": "Right Now Likes",
                "ordering": ["-created_at"],
                "unique_together": {("post", "profile")},
            },
        ),
    ]
