# Generated by Django 5.0.2 on 2026-05-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_rightnowcomment_rightnowlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_banned_from_nexus",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Completely hide this company from the public Company Nexus directory (spam/inappropriate).",
                verbose_name="Banned from Nexus",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this company to the absolute top of the Company Nexus Feed.",
                verbose_name="Admin Selected (Pinned)",
            ),
        ),
    ]
