# Generated by Django 5.0.2 on 2026-05-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_company_is_banned_from_nexus_company_is_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="oracle_score",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=0,
                help_text="The exact 1-100 score calculated by the Oracle. Used for granular feed sorting.",
                verbose_name="Raw AI Score",
            ),
        ),
    ]
