# Generated by Django 5.0.2 on 2026-06-26 10:30

import django.core.validators
import profiles.models.new_unified_profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_userprofile_oracle_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioproject",
            name="category",
            field=models.CharField(
                choices=[
                    ("SOFTWARE_DATA", "Software, AI & Data Science"),
                    ("HARDWARE_ROBOTICS", "Hardware, Engineering & Robotics"),
                    ("MEDICAL_CLINICAL", "Medicine, Healthcare & Biotech"),
                    ("LEGAL_POLICY", "Law, Public Policy & Gov"),
                    ("SCIENCE_RESEARCH", "Academic Science & Lab Research"),
                    ("DESIGN_UX", "UI/UX, Product & Graphic Design"),
                    ("ARCHITECTURE_CIVIL", "Architecture & Civil Engineering"),
                    ("BUSINESS_FINANCE", "Business, Finance & Startups"),
                    ("MARKETING_MEDIA", "Marketing, Journalism & Media"),
                    ("ARTS_CREATIVE", "Film, Music, Photography & Fine Arts"),
                    ("EDUCATION_TRAINING", "Education, Curriculum & Training"),
                    ("OPERATIONS_TRADES", "Operations, Culinary & Skilled Trades"),
                    ("OTHER", "Interdisciplinary / Niche"),
                ],
                db_index=True,
                default="OTHER",
                help_text="The core industry of this project.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="portfolioproject",
            name="meta_attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores infinite profession-specific inputs natively (e.g., {'jurisdiction': 'NY'} or {'tech_stack': ['React']})",
                verbose_name="Domain Specific Data",
            ),
        ),
        migrations.AddField(
            model_name="projectgallery",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Visual / Screenshot"),
                    ("DOCUMENT", "PDF Document / Research Paper / Case File"),
                    ("EMBED", "External Embed (Figma, YouTube, Spotify)"),
                ],
                default="IMAGE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectgallery",
            name="document_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=profiles.models.new_unified_profile.project_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="projectgallery",
            name="external_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="portfolioproject",
            name="context",
            field=models.CharField(
                choices=[
                    ("PRACTICE", "Learning / Bootcamp Project"),
                    ("REAL_WORLD", "Real-world / Client Project"),
                    ("STARTUP", "Startup / Own Company"),
                    ("PUBLISHED", "Published / Peer-Reviewed"),
                ],
                default="PRACTICE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="projectgallery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=profiles.models.new_unified_profile.project_image_path,
            ),
        ),
    ]
