# Generated by Django 5.0.2 on 2026-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0022_alter_portfolioproject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_TIME", "Full-time"),
                    ("PART_TIME", "Part-time"),
                    ("CONTRACT", "Contract"),
                    ("INTERNSHIP", "Internship"),
                    ("FREELANCE", "Freelance"),
                    ("VOLUNTEER", "Volunteer"),
                    ("APPRENTICESHIP", "Apprenticeship"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
