# Generated by Django 5.0.2 on 2026-06-28 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0023_workexperience_employment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[
                            ("am", "Amharic"),
                            ("om", "Oromo"),
                            ("ti", "Tigrinya"),
                            ("so", "Somali"),
                            ("aa", "Afar"),
                            ("sid", "Sidamo"),
                            ("wal", "Wolaytta"),
                            ("gur", "Gurage (General)"),
                            ("en", "English"),
                            ("ar", "Arabic"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("de", "German"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                            ("pt", "Portuguese"),
                            ("ru", "Russian"),
                            ("it", "Italian"),
                            ("hi", "Hindi"),
                            ("ko", "Korean"),
                            ("tr", "Turkish"),
                            ("fa", "Persian"),
                            ("sw", "Swahili"),
                            ("OTHER", "Other (Custom)"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="Language Code",
                    ),
                ),
                (
                    "custom_language_name",
                    models.CharField(
                        blank=True,
                        help_text="Required if 'Other' is selected",
                        max_length=100,
                        null=True,
                        verbose_name="Custom Language Name",
                    ),
                ),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("NATIVE", "Native"),
                            ("FLUENT", "Fluent / Professional"),
                            ("INTERMEDIATE", "Intermediate / Conversational"),
                            ("BASIC", "Basic / Beginner"),
                        ],
                        db_index=True,
                        default="INTERMEDIATE",
                        max_length=20,
                        verbose_name="Proficiency Level",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as your primary/native language",
                        verbose_name="Primary Language",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="profiles.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["-is_primary", "order", "language_code"],
            },
        ),
    ]
