# Generated by Django 5.0.2 on 2026-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0024_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="rightnowpost",
            name="is_admin_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, this post is selected by admin to appear in the feed.",
                verbose_name="Admin Curated",
            ),
        ),
    ]
