# Generated by Django 5.0.2 on 2026-06-29 10:04

from django.db import migrations


def auto_select_existing_posts(apps, schema_editor):
    """Auto-select all existing published posts to prevent feed disruption."""
    RightNowPost = apps.get_model('profiles', 'RightNowPost')
    RightNowPost.objects.filter(is_published=True).update(is_admin_selected=True)


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_rightnowpost_is_admin_selected"),
    ]

    operations = [
        migrations.RunPython(auto_select_existing_posts, migrations.RunPython.noop),
    ]
