# Generated by Django 5.0.2 on 2026-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0026_auto_20260629_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolioproject",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SOFTWARE_DATA", "Software, AI & Data Science"),
                    ("HARDWARE_ROBOTICS", "Hardware, Engineering & Robotics"),
                    ("MEDICAL_CLINICAL", "Medicine, Healthcare & Biotech"),
                    ("LEGAL_POLICY", "Law, Public Policy & Gov"),
                    ("SCIENCE_RESEARCH", "Academic Science & Lab Research"),
                    ("DESIGN_UX", "UI/UX, Product & Graphic Design"),
                    ("ARCHITECTURE_CIVIL", "Architecture & Civil Engineering"),
                    ("BUSINESS_FINANCE", "Business, Finance & Startups"),
                    ("MARKETING_MEDIA", "Marketing, Journalism & Media"),
                    ("ARTS_CREATIVE", "Film, Music, Photography & Fine Arts"),
                    ("EDUCATION_TRAINING", "Education, Curriculum & Training"),
                    ("OPERATIONS_TRADES", "Operations, Culinary & Skilled Trades"),
                    ("OTHER", "Interdisciplinary / Niche"),
                ],
                db_index=True,
                help_text="The core industry of this project.",
                max_length=30,
            ),
        ),
    ]
