# Generated by Django 5.0.2 on 2026-07-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0028_alter_portfolioproject_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="current_usage",
            field=models.TextField(
                blank=True,
                help_text="Describe how you currently apply this skill in your work or projects",
                verbose_name="How do you currently use this skill?",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="context",
            field=models.TextField(
                blank=True,
                help_text="Describe how you have used this skill in the past",
                verbose_name="How have you used this skill?",
            ),
        ),
    ]
