# Generated by Django 5.0.2 on 2026-07-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0029_skill_current_usage_alter_skill_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="current_usage",
        ),
        migrations.AlterField(
            model_name="skill",
            name="context",
            field=models.TextField(
                blank=True,
                help_text="Explain how you used this skill and how it helps you in your field",
                verbose_name="Context / Motivation",
            ),
        ),
    ]
