# Generated by Django 5.0.2 on 2026-07-01 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0030_remove_skill_current_usage_alter_skill_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="context",
            field=models.TextField(blank=True, verbose_name="Context / Motivation"),
        ),
        migrations.CreateModel(
            name="CompanyInvitation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "profile_url",
                    models.URLField(blank=True, null=True, verbose_name="Profile URL"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner / Primary Contact"),
                            ("ADMIN", "Administrator"),
                            ("EDITOR", "Content Editor"),
                            ("ALUMNI", "Past Member (No Access)"),
                        ],
                        default="EDITOR",
                        max_length=15,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=100, verbose_name="Job Title"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Acceptance"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="profiles.company",
                    ),
                ),
                (
                    "invited_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Invitation",
                "verbose_name_plural": "Company Invitations",
                "ordering": ["-created_at"],
            },
        ),
    ]
