# Generated by Django 5.0.2 on 2026-07-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0032_update_language_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="date_display",
            field=models.CharField(
                blank=True,
                help_text="Enter date in any format (e.g., '2023-2024', 'Summer 2023', '2023 - Present'). This will be displayed on your portfolio.",
                max_length=100,
                verbose_name="Custom Date Display",
            ),
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
