# Generated by Django 5.0.2 on 2026-07-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0033_workexperience_date_display_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if the user has completed a complete profile and is verified by the platform",
                verbose_name="Profile Verified",
            ),
        ),
    ]
