# Generated by Django 5.0.2 on 2026-07-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_alter_company_looking_for"),
        ("profiles", "0035_service_servicegallery"),
    ]

    operations = []
