# Generated by Django 5.0.2 on 2026-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0036_merge_20260719_1253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expertcredential",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="expertexperience",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="expertheadline",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="expertprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="jobpreference",
            name="expert",
        ),
        migrations.RemoveField(
            model_name="expertskill",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="expertproject",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="expertthought",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="projectgalleryimage",
            name="project",
        ),
        migrations.RemoveField(
            model_name="founderprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="growthlog",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="learningtarget",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="project",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="project",
        ),
        migrations.RemoveField(
            model_name="visionaryprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="visionblock",
            name="profile",
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="looking_for",
            field=models.CharField(
                choices=[
                    ("Expanding", "Expanding"),
                    ("FUNDRAISING", "Seeking Investment"),
                    ("HIRING", "Hiring"),
                    ("PARTNERING", "Seeking Co-Founders"),
                    ("SALES", "Seeking B2B Clients"),
                ],
                default="Expanding",
                max_length=20,
                verbose_name="Current Company Objective",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="companycontactmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companycontactmethod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="companymember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companymember",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="companynews",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companynews",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="companysociallink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companysociallink",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="ExpertCredential",
        ),
        migrations.DeleteModel(
            name="ExpertExperience",
        ),
        migrations.DeleteModel(
            name="ExpertHeadline",
        ),
        migrations.DeleteModel(
            name="JobPreference",
        ),
        migrations.DeleteModel(
            name="ExpertSkill",
        ),
        migrations.DeleteModel(
            name="ExpertProfile",
        ),
        migrations.DeleteModel(
            name="ExpertThought",
        ),
        migrations.DeleteModel(
            name="ExpertProject",
        ),
        migrations.DeleteModel(
            name="ProjectGalleryImage",
        ),
        migrations.DeleteModel(
            name="FounderProfile",
        ),
        migrations.DeleteModel(
            name="GrowthLog",
        ),
        migrations.DeleteModel(
            name="LearningTarget",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectImage",
        ),
        migrations.DeleteModel(
            name="VisionaryProfile",
        ),
        migrations.DeleteModel(
            name="VisionBlock",
        ),
    ]
