# Generated by Django 5.0.2 on 2026-07-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0037_remove_expertcredential_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicegallery",
            name="service",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
        migrations.DeleteModel(
            name="ServiceGallery",
        ),
    ]
