# Generated by Django 5.0.2 on 2026-03-01 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_slug', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='public/assets/')),
                ('target_link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['zone_slug', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteTextAsset',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_rich_text', models.BooleanField(default=False)),
            ],
        ),
    ]
