# Generated by Django 5.0.2 on 2026-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitemediaasset",
            options={
                "ordering": ["zone_slug", "order"],
                "verbose_name": "Site Media Asset",
                "verbose_name_plural": "Site Media Assets",
            },
        ),
        migrations.AlterModelOptions(
            name="sitetextasset",
            options={
                "verbose_name": "Site Text Asset",
                "verbose_name_plural": "Site Text Assets",
            },
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="image",
            field=models.ImageField(
                help_text="Media asset file. Optimized for web display",
                upload_to="public/assets/",
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Controls visibility on the platform"
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order within the zone"
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="target_link",
            field=models.URLField(
                blank=True, help_text="Optional click-through URL for the asset"
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title for admin reference",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="sitemediaasset",
            name="zone_slug",
            field=models.CharField(
                help_text="Zone identifier (e.g., HOME_HERO, SIDEBAR_BANNER)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sitetextasset",
            name="content",
            field=models.TextField(
                help_text="Text content. Supports HTML for rich formatting"
            ),
        ),
        migrations.AlterField(
            model_name="sitetextasset",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Admin description for content identification",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sitetextasset",
            name="is_rich_text",
            field=models.BooleanField(
                default=False, help_text="Enable HTML rendering for this content"
            ),
        ),
        migrations.AlterField(
            model_name="sitetextasset",
            name="key",
            field=models.CharField(
                help_text="Unique identifier for the text content",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="sitemediaasset",
            index=models.Index(
                fields=["zone_slug", "order", "is_active"],
                name="core_siteme_zone_sl_198fd0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sitemediaasset",
            index=models.Index(
                fields=["is_active"], name="core_siteme_is_acti_019884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sitetextasset",
            index=models.Index(fields=["key"], name="core_sitete_key_839e02_idx"),
        ),
    ]
