# Generated by Django 5.0.2 on 2026-07-22 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_sitemediaasset_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteMediaAsset",
        ),
        migrations.DeleteModel(
            name="SiteTextAsset",
        ),
    ]
