# Generated by Django 5.0.2 on 2026-03-02 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("BUILDING", "🛠️ Building (Proof of Work)"),
                            ("SEEKING", "🔍 Seeking (Collaborators/Help)"),
                            ("LAUNCHING", "🚀 Launching (Showcase)"),
                            ("CONNECTING", "☕ Connecting (Like Minds)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Punchy headline (e.g., 'Starting a new garage in Addis')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Deeper context (optional)", null=True
                    ),
                ),
                (
                    "interest_tag",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g. Real Estate, Automotive, Tech (optional)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Attach an image (optional)",
                        null=True,
                        upload_to="signals/covers/",
                    ),
                ),
                (
                    "external_link",
                    models.URLField(
                        blank=True,
                        help_text="Live URL, GitHub, or Website (optional)",
                        null=True,
                    ),
                ),
                (
                    "is_seeking_partner",
                    models.BooleanField(
                        default=False, help_text="Is this a Co-Founder/Equity role?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expert_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.expertproject",
                    ),
                ),
                (
                    "visionary_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="profiles.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Signal",
                "verbose_name_plural": "Network Signals",
                "ordering": ["-created_at"],
            },
        ),
    ]
