# Generated by Django 5.0.2 on 2026-03-03 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="A concise, professional title for the work.",
                        max_length=150,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed overview of the project objectives and roadmap."
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("STARTUP", "Startup / Business"),
                            ("SPECIFIC_PROJECT", "Specific Project"),
                        ],
                        default="STARTUP",
                        max_length=20,
                    ),
                ),
                (
                    "project_stage",
                    models.CharField(
                        choices=[
                            ("IDEATION", "Ideation & Discovery"),
                            ("PROTOTYPING", "Prototyping & Build"),
                            ("VALIDATION", "Market Validation"),
                            ("TRACTION", "Early Traction"),
                            ("EXPANSION", "Scale & Expansion"),
                        ],
                        default="IDEATION",
                        max_length=20,
                    ),
                ),
                (
                    "need_type",
                    models.CharField(
                        choices=[
                            ("COFOUNDER", "Co-Founder"),
                            ("COLLABORATOR", "Project Collaborator"),
                            ("TEAM", "Team Member"),
                            ("ADVISOR", "Advisor / Mentor"),
                            ("FEEDBACK", "Feedback & Testing"),
                        ],
                        default="COLLABORATOR",
                        max_length=20,
                    ),
                ),
                (
                    "looking_for",
                    models.TextField(
                        help_text="Specify the expertise, commitment, and background required."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Visible in the feed while active."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Signal",
        ),
        migrations.AddIndex(
            model_name="networkpost",
            index=models.Index(
                fields=["project_type", "need_type", "project_stage", "is_active"],
                name="network_net_project_0cf40c_idx",
            ),
        ),
    ]
