# Generated by Django 5.0.2 on 2026-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_networkpost_headline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkpost",
            name="headline",
            field=models.CharField(
                help_text="A concise, professional title for the work.", max_length=1500
            ),
        ),
    ]
