# Generated by Django 5.0.2 on 2026-03-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_alter_networkpost_headline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networkpost",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Network Post",
                "verbose_name_plural": "Network Posts",
            },
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="author",
            field=models.ForeignKey(
                help_text="Project author and primary contact",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="description",
            field=models.TextField(
                help_text="Detailed overview of the project objectives, vision, and roadmap"
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="headline",
            field=models.CharField(
                help_text="A concise, professional title for the collaboration opportunity",
                max_length=1500,
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Controls visibility in the network feed"
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="looking_for",
            field=models.TextField(
                help_text="Detailed description of expertise, commitment, and background required"
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="need_type",
            field=models.CharField(
                choices=[
                    ("COFOUNDER", "Co-Founder"),
                    ("COLLABORATOR", "Project Collaborator"),
                    ("TEAM", "Team Member"),
                    ("ADVISOR", "Advisor / Mentor"),
                    ("FEEDBACK", "Feedback & Testing"),
                ],
                default="COLLABORATOR",
                help_text="Type of partnership or collaboration sought",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="project_stage",
            field=models.CharField(
                choices=[
                    ("IDEATION", "Ideation & Discovery"),
                    ("PROTOTYPING", "Prototyping & Build"),
                    ("VALIDATION", "Market Validation"),
                    ("TRACTION", "Early Traction"),
                    ("EXPANSION", "Scale & Expansion"),
                ],
                default="IDEATION",
                help_text="Current development stage of the project",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="networkpost",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("STARTUP", "Startup / Business"),
                    ("SPECIFIC_PROJECT", "Specific Project"),
                ],
                default="STARTUP",
                help_text="Nature and scope of the project",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="networkpost",
            index=models.Index(
                fields=["author", "created_at"], name="network_net_author__6a930b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="networkpost",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="network_net_is_acti_572f5a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="networkpost",
            index=models.Index(
                fields=["project_stage", "need_type"],
                name="network_net_project_c2eaab_idx",
            ),
        ),
    ]
