# Generated by Django 5.0.2 on 2026-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chatmessage",
            new_name="chat_chatme_sender__34ee69_idx",
            old_name="chat_chatmessage_sender_receiver_idx",
        ),
        migrations.AlterField(
            model_name="companymessagetoadmin",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companymessagetoadmin",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
    ]
