# Generated by Django 5.0.2 on 2026-03-01 20:22

import accounts.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityContributor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('telegram_username', models.CharField(max_length=100)),
                ('contribution_area', models.CharField(max_length=200)),
                ('message', models.TextField(verbose_name='Why CoreLink?')),
                ('is_contacted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'verbose_name': 'Community Volunteer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+251911234567'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('corelink_id', models.CharField(blank=True, db_index=True, help_text='Human-readable unique ID (e.g., VIS-2024-001).', max_length=20, null=True, unique=True, verbose_name='Public Badge')),
                ('role', models.CharField(choices=[('FOUNDER', 'Founder'), ('EXPERT', 'Expert'), ('VISIONARY', 'Visionary'), ('ADMIN', 'Admin')], db_index=True, default='VISIONARY', max_length=10)),
                ('full_name', models.CharField(max_length=150, verbose_name='Legal Name')),
                ('telegram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Handle')),
                ('current_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Location')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='public/avatars/', verbose_name='Avatar')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='public/covers/', verbose_name='Cover Image')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verification Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Switch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
                'db_table': 'corelink_identity_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Staff',
                'verbose_name_plural': 'Admin Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
        ),
        migrations.CreateModel(
            name='IDSequence',
            fields=[
                ('prefix', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Role Prefix')),
                ('year', models.IntegerField(verbose_name='Year Code')),
                ('last_number', models.IntegerField(default=0, verbose_name='Last Sequence Number')),
            ],
            options={
                'verbose_name': 'ID Sequence Counter',
                'unique_together': {('prefix', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UniversalContactMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50, verbose_name='Platform / Method')),
                ('value', models.CharField(max_length=255, verbose_name='Contact Value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Method',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('EXPERT', 'Expert'), ('VISIONARY', 'Visionary'), ('FOUNDER', 'Founder')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '🟡 Pending Review'), ('APPROVED', '🟢 Approved'), ('REJECTED', '🔴 Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=accounts.models.application_cv_path)),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('admin_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'role_type'], name='accounts_ap_status_b1887e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UniversalSocialLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=50, verbose_name='Platform')),
                ('url', models.URLField(max_length=500, verbose_name='URL Payload')),
                ('icon_slug', models.CharField(default='link', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Link',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['user', 'order'], name='accounts_un_user_id_27c84a_idx')],
            },
        ),
    ]
