# Generated by Django 5.0.2 on 2026-03-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, you will vanish from the Network/Nexus, but can still apply to jobs.",
                verbose_name="Public Visibility",
            ),
        ),
    ]
