# Generated by Django 5.0.2 on 2026-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_nexus_visible",
            field=models.BooleanField(
                default=True,
                help_text="Check this to secretly hide the user from the Nexus feed without notifying them. Their dashboard will still say 'Public'.",
                verbose_name="Shadowbanned (Hidden)",
            ),
        ),
    ]
