# Generated by Django 5.0.2 on 2026-03-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_nexus_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_nexus_visible",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck this box to BAN the user from the public Nexus feed.",
                verbose_name="Visible in Public Feed",
            ),
        ),
    ]
