# Generated by Django 5.0.2 on 2026-03-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_is_nexus_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top of the Nexus Feed.",
                verbose_name="Admin Selected",
            ),
        ),
    ]
