# Generated by Django 5.0.2 on 2026-03-15 12:13

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_is_selected"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Member Application",
                "verbose_name_plural": "Member Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="communitycontributor",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Community Volunteer",
                "verbose_name_plural": "Community Volunteers",
            },
        ),
        migrations.AlterModelOptions(
            name="idsequence",
            options={
                "verbose_name": "ID Sequence Counter",
                "verbose_name_plural": "ID Sequence Counters",
            },
        ),
        migrations.AlterModelOptions(
            name="universalcontactmethod",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Contact Method",
                "verbose_name_plural": "Contact Methods",
            },
        ),
        migrations.AlterModelOptions(
            name="universalsociallink",
            options={
                "ordering": ["order"],
                "verbose_name": "Social Link",
                "verbose_name_plural": "Social Links",
            },
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="admin_notes",
            field=models.TextField(
                blank=True, help_text="Admin review notes and feedback"
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Supporting CV or document",
                null=True,
                upload_to=accounts.models.application_cv_path,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("EXPERT", "Expert"),
                    ("VISIONARY", "Visionary"),
                    ("FOUNDER", "Founder"),
                ],
                db_index=True,
                help_text="Target role being applied for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "🟡 Pending Review"),
                    ("APPROVED", "🟢 Approved"),
                    ("REJECTED", "🔴 Rejected"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Current application status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="submission_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional application metadata"
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="applicationrequest",
            name="user",
            field=models.ForeignKey(
                help_text="User requesting role upgrade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="contribution_area",
            field=models.CharField(
                help_text="Area of interest/expertise", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="full_name",
            field=models.CharField(
                help_text="Volunteer's complete name", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="is_contacted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the volunteer has been contacted",
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="message",
            field=models.TextField(
                help_text="Motivation for joining the community",
                verbose_name="Why CoreLink?",
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="telegram_username",
            field=models.CharField(
                help_text="@username for Telegram contact", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="communitycontributor",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture. Auto-optimized to WebP format",
                null=True,
                upload_to="public/avatars/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="corelink_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable unique ID (e.g., VIS-2024-001). Auto-generated.",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Public Badge",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Header image. Role-based fallbacks available",
                null=True,
                upload_to="public/covers/",
                verbose_name="Cover Image",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="current_location",
            field=models.CharField(
                blank=True,
                help_text="City, Country for networking purposes",
                max_length=100,
                null=True,
                verbose_name="Current Location",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(
                help_text="Official name for professional correspondence",
                max_length=150,
                verbose_name="Legal Name",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Account suspension control",
                verbose_name="Active Switch",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_nexus_visible",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to ban user from public Nexus feed",
                verbose_name="Visible in Public Feed",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="If unchecked, user vanishes from Network/Nexus but can apply to jobs",
                verbose_name="Public Visibility",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top of the Nexus Feed",
                verbose_name="Admin Selected",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="Identity verification completion status",
                verbose_name="Verification Status",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                error_messages={
                    "unique": "A user with this phone number already exists."
                },
                help_text="Primary authentication identifier. Format: +251911234567",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+251911234567'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("FOUNDER", "Founder"),
                    ("EXPERT", "Expert"),
                    ("VISIONARY", "Visionary"),
                    ("ADMIN", "Admin"),
                ],
                db_index=True,
                default="VISIONARY",
                help_text="Determines platform access and profile features",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="telegram_handle",
            field=models.CharField(
                blank=True,
                help_text="@username for community communication",
                max_length=100,
                null=True,
                verbose_name="Telegram Handle",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="idsequence",
            name="last_number",
            field=models.IntegerField(
                default=0,
                help_text="Last assigned sequence number",
                verbose_name="Last Sequence Number",
            ),
        ),
        migrations.AlterField(
            model_name="idsequence",
            name="prefix",
            field=models.CharField(
                help_text="Role identifier (e.g., EXP, VIS, FND)",
                max_length=10,
                primary_key=True,
                serialize=False,
                verbose_name="Role Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="idsequence",
            name="year",
            field=models.IntegerField(
                help_text="Calendar year for sequence grouping",
                verbose_name="Year Code",
            ),
        ),
        migrations.AlterField(
            model_name="universalcontactmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="universalcontactmethod",
            name="type",
            field=models.CharField(
                help_text="e.g., Email, Phone, WhatsApp, Telegram",
                max_length=50,
                verbose_name="Platform / Method",
            ),
        ),
        migrations.AlterField(
            model_name="universalcontactmethod",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="universalcontactmethod",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this contact method",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_methods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="universalcontactmethod",
            name="value",
            field=models.CharField(
                help_text="Actual contact information (address, number, handle)",
                max_length=255,
                verbose_name="Contact Value",
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="icon_slug",
            field=models.CharField(
                default="link",
                help_text="Icon identifier for UI rendering",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order on profile"
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="platform_name",
            field=models.CharField(
                help_text="e.g., LinkedIn, Twitter, GitHub",
                max_length=50,
                verbose_name="Platform",
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="url",
            field=models.URLField(
                help_text="Full URL to the social profile",
                max_length=500,
                verbose_name="URL Payload",
            ),
        ),
        migrations.AlterField(
            model_name="universalsociallink",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this social link",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="applicationrequest",
            index=models.Index(
                fields=["user", "status"], name="accounts_ap_user_id_26d466_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communitycontributor",
            index=models.Index(
                fields=["is_contacted", "created_at"],
                name="accounts_co_is_cont_a758da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["phone_number"], name="corelink_id_phone_n_3b782c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["corelink_id"], name="corelink_id_corelin_ed1a5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["role", "is_public"], name="corelink_id_role_a778a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["is_selected", "created_at"],
                name="corelink_id_is_sele_766af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="idsequence",
            index=models.Index(
                fields=["prefix", "year"], name="accounts_id_prefix_76cab7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="universalcontactmethod",
            index=models.Index(
                fields=["user", "type"], name="accounts_un_user_id_a4832a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="universalsociallink",
            index=models.Index(
                fields=["platform_name"], name="accounts_un_platfor_781fb0_idx"
            ),
        ),
    ]
