# Generated by Django 5.0.2 on 2026-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_applicationrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
