# Generated by Django 5.0.2 on 2026-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_applicationrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_otp_code",
            field=models.CharField(
                blank=True,
                help_text="Temporary OTP code for email verification",
                max_length=6,
                null=True,
                verbose_name="Email OTP Code",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_otp_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Expiration timestamp for the active email OTP",
                null=True,
                verbose_name="Email OTP Expiry",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="True when email OTP or Google verification is complete",
                verbose_name="Email Verified",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="google_sub",
            field=models.CharField(
                blank=True,
                help_text="Unique Google account subject identifier",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Google Subject ID",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="customuser",
                    name="email",
                    field=models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Used for OTP verification and Google sign-in",
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
            ],
        ),
    ]
