# Generated by Django 5.0.2 on 2026-04-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_add_google_sub_if_missing"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="customuser",
                    name="email_otp_code",
                    field=models.CharField(
                        blank=True,
                        db_column="email_otp",
                        help_text="Temporary OTP code for email verification",
                        max_length=6,
                        null=True,
                        verbose_name="Email OTP Code",
                    ),
                ),
                migrations.AlterField(
                    model_name="customuser",
                    name="email_otp_expires_at",
                    field=models.DateTimeField(
                        blank=True,
                        db_column="email_otp_created_at",
                        help_text="Expiration timestamp for the active email OTP",
                        null=True,
                        verbose_name="Email OTP Expiry",
                    ),
                ),
                migrations.AlterField(
                    model_name="customuser",
                    name="email_verified",
                    field=models.BooleanField(
                        db_column="is_email_verified",
                        default=False,
                        help_text="True when email OTP or Google verification is complete",
                        verbose_name="Email Verified",
                    ),
                ),
            ],
        ),
    ]
