# Generated by Django 5.0.2 on 2026-03-26 22:00

from django.db import migrations, models

def fix_duplicate_emails(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    # Set empty strings to NULL to avoid duplicate violation in Postgres
    # (assuming Postgres unique constraint allows multiple NULLs but not multiple empty strings)
    # If there are actual duplicate emails, we might need a more aggressive fix.
    CustomUser.objects.filter(email='').update(email=None)
    
    # Check for actual duplicate non-null emails
    from django.db.models import Count
    duplicates = (
        CustomUser.objects.values('email')
        .annotate(email_count=Count('id'))
        .filter(email_count__gt=1)
        .exclude(email=None)
    )
    
    for duplicate in duplicates:
        email = duplicate['email']
        users = CustomUser.objects.filter(email=email).order_by('id')
        # Keep the first one, and for others, append their id to the email
        for user in users[1:]:
            user.email = f"dup_{user.id}_{user.email}"
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_country_city_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Indicates if the user's primary email has been verified", verbose_name='Email Verified'),
        ),
        # 1. First make the field nullable to allow NULLs for the cleanup script
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email for notifications and account recovery', max_length=254, null=True, verbose_name='Email Address'),
        ),
        # 2. Run the cleanup script to replace empty strings with NULLs and handle real duplicates
        migrations.RunPython(fix_duplicate_emails, reverse_code=migrations.RunPython.noop),
        # 3. Finally apply the unique constraint
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email for notifications and account recovery', max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
    ]
