# Generated by Django 5.0.2 on 2026-03-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_is_email_verified_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(blank=True, help_text='One-time password for email verification', max_length=6, null=True, verbose_name='Email OTP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the email OTP was generated', null=True, verbose_name='OTP Created At'),
        ),
    ]
