# Generated by Django 5.0.2 on 2026-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_email_otp_customuser_email_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycontributor',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary email for communication', max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
