# Generated by Django 5.0.2 on 2026-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_communitycontributor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_otp',
            field=models.CharField(blank=True, help_text='One-time password for email verification', max_length=128, null=True, verbose_name='Email OTP'),
        ),
    ]
