# Generated by Django 5.0.2 on 2026-03-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_currentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, help_text='User city selected from verified cities', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, help_text='User country selected from verified countries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.country'),
        ),
    ]
