# Generated by Django 5.0.2 on 2026-04-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_backfill_first_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_banned_from_right_now",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Completely hide this user from the Right Now feed (if they post spam/generic missions).",
                verbose_name="Banned from Right Now Feed",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_pinned_in_right_now",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the absolute top of the Right Now (Live Intent) feed.",
                verbose_name="Pinned in Right Now Feed",
            ),
        ),
    ]
