# Generated by Django 5.0.2 on 2026-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_customuser_is_banned_from_right_now_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_hero_avatar_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top hero section avatar cluster on the landing page.",
                verbose_name="Home Page Avatar Selected",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_home_profile_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the Talent Network card section on the landing page.",
                verbose_name="Home Page Profile Selected",
            ),
        ),
    ]
