# Generated by Django 5.0.2 on 2026-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0018_merge_0011_legacy_email_verified_default_0017_customuser_is_hero_avatar_selected_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_otp_expires_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Primary email for notifications and account recovery",
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
