# Generated by Django 5.0.2 on 2026-06-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_remove_customuser_email_otp_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_contacted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Check this if the user has been reached out to by our team.",
                verbose_name="Contacted Status",
            ),
        ),
    ]
