# Generated by Django 5.0.2 on 2026-06-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_customuser_is_contacted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_hero_avatar_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top hero section avatar cluster on the landing page.",
                verbose_name="Hero Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_home_profile_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the Talent Network card section on the landing page.",
                verbose_name="Home Profile",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_nexus_visible",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck to ban user from public Nexus feed",
                verbose_name="Public Feed",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top of the Nexus Feed",
                verbose_name="Admin Pick",
            ),
        ),
    ]
