# Generated by Django 5.0.2 on 2026-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_customuser_is_hero_avatar_selected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_top_10",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the Top 10 section (displayed first in Nexus Feed, random order).",
                verbose_name="Top 10 Talent",
            ),
        ),
    ]
