# Generated by Django 5.0.2 on 2026-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_customuser_is_top_10"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_verified",
            field=models.BooleanField(
                default=False,
                help_text="Check this to mark the user's profile as verified on the public portfolio page",
                verbose_name="Profile Verified",
            ),
        ),
    ]
