# Generated by Django 5.0.2 on 2026-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_customuser_profile_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_page_top",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top section of the home page.",
                verbose_name="Home Page Top",
            ),
        ),
    ]
