# Generated by Django 5.0.2 on 2026-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_customuser_home_page_top"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="home_page_top",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top section of home page",
                verbose_name="Home Page Top",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_banned_from_right_now",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Hide this user from the Right Now feed",
                verbose_name="Banned from Right Now Feed",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_hero_avatar_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the hero section on landing page",
                verbose_name="Hero Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_home_profile_selected",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the Talent Network section on landing page",
                verbose_name="Home Profile",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_pinned_in_right_now",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the top of the Right Now feed",
                verbose_name="Pinned in Right Now Feed",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_top_10",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Pin this user to the Top 10 section on Nexus Feed",
                verbose_name="Top 10 Talent",
            ),
        ),
    ]
