# Generated by Django 5.0.2 on 2026-03-01 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('ai_aliases', models.JSONField(blank=True, default=list, help_text="e.g.,['VueJS', 'Vue.js']")),
                ('category', models.CharField(blank=True, help_text="e.g., 'Engineering', 'Design'", max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_official_admin_post', models.BooleanField(default=False)),
                ('is_external', models.BooleanField(default=False, help_text='Is this a link to an outside application?')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('external_company_name', models.CharField(blank=True, max_length=200)),
                ('external_company_logo', models.ImageField(blank=True, null=True, upload_to='opportunities/logos/')),
                ('source_name', models.CharField(blank=True, help_text="e.g. 'Telegram', 'EthioJobs'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Markdown supported.', verbose_name='The Mission Narrative')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='opportunities/covers/')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full-Time Role'), ('PART_TIME', 'Part-Time Role'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Freelance / Contract'), ('GIG', 'Gig / Quick Task'), ('CHALLENGE', 'Business Challenge'), ('ADVISORY', 'Advisory / Mentorship'), ('VOLUNTEER', 'Volunteer / Social Impact'), ('COFOUNDER', 'Co-Founder')], default='FULL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Live'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='Addis Ababa', max_length=100, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('compensation_text', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deadline_date', models.DateField(blank=True, help_text='Specific date for calendar sorting (Optional).', null=True)),
                ('deadline_text', models.CharField(blank=True, help_text="Free text if date is unknown, e.g., 'Rolling basis', 'End of month'.", max_length=150)),
                ('is_open_ended', models.BooleanField(default=True, help_text='Check if this job has no deadline.')),
                ('requires_challenge', models.BooleanField(default=False)),
                ('challenge_description', models.TextField(blank=True, help_text="e.g. 'Attach a project where you used React hooks.'")),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('ai_metadata', models.JSONField(blank=True, default=dict, help_text='Store vector embedding IDs, auto-generated summaries, and semantic search data here.')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='profiles.company')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='opportunities', to='opportunities.skill')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_note', models.TextField(blank=True, help_text="The 'Why Me' pitch.", max_length=2000)),
                ('status', models.CharField(choices=[('LINKED', 'Linked'), ('VIEWED', 'Recruiter Viewed'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW', 'Interview'), ('REJECTED', 'Not a Fit'), ('HIRED', 'Hired')], default='LINKED', max_length=20)),
                ('match_score', models.FloatField(default=0.0, help_text='AI Compatibility Score (0-100)')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text="Store AI reasoning here (e.g. {'strengths': ['Python', 'Django'], 'weaknesses': ['AWS']})")),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('attached_project', models.ForeignKey(blank=True, help_text='The specific portfolio item that proves competence.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.project')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.jobpost')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['job', 'status'], name='opportuniti_job_id_9e6d65_idx'), models.Index(fields=['applicant', 'status'], name='opportuniti_applica_f47bc4_idx')],
                'unique_together': {('job', 'applicant')},
            },
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['status', 'published_at'], name='opportuniti_status_9dcfd9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['job_type', 'is_remote'], name='opportuniti_job_typ_1f9938_idx'),
        ),
        migrations.AddIndex(
            model_name='jobpost',
            index=models.Index(fields=['deadline_date'], name='opportuniti_deadlin_019546_idx'),
        ),
    ]
