# Generated by Django 5.0.2 on 2026-03-01 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="level",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student / Intern"),
                    ("ENTRY", "Entry Level / Junior"),
                    ("MID", "Mid Level"),
                    ("SENIOR", "Senior Level"),
                    ("LEAD", "Lead / Manager"),
                    ("EXECUTIVE", "Executive / Director"),
                    ("ANY", "Any Level / Not Applicable"),
                ],
                default="ANY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to external application.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="is_external",
            field=models.BooleanField(
                default=False, help_text="Is this an outside application?"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(fields=["level"], name="opportuniti_level_0c87b7_idx"),
        ),
    ]
