# Generated by Django 5.0.2 on 2026-03-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_jobpost_level_alter_jobpost_external_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student / Intern"),
                    ("ENTRY", "Entry Level / Junior"),
                    ("MID", "Mid Level"),
                    ("SENIOR", "Senior Level"),
                    ("LEAD", "Lead / Manager"),
                    ("EXECUTIVE", "Executive / Director"),
                    ("ANY", "Any Level / Not Applicable"),
                ],
                help_text="Optional: Leave blank if not applicable or posting in bulk.",
                max_length=20,
                null=True,
            ),
        ),
    ]
