# Generated by Django 5.0.2 on 2026-03-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_alter_jobpost_level"),
        ("profiles", "0012_alter_company_created_at_alter_company_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={
                "ordering": ["-match_score", "-created_at"],
                "verbose_name": "Job Application",
                "verbose_name_plural": "Job Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="jobpost",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "Job Opportunity",
                "verbose_name_plural": "Job Opportunities",
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.AddField(
            model_name="jobpost",
            name="ai_match_score",
            field=models.FloatField(
                default=0.0, help_text="AI-calculated quality score (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed skill description for AI context"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="is_trending",
            field=models.BooleanField(
                default=False, help_text="Mark as trending skill for highlighting"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="proficiency_levels",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Available proficiency levels (e.g., ['Junior', 'Senior', 'Expert'])",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="ai_analysis",
            field=models.JSONField(
                blank=True, default=dict, help_text="Detailed AI analysis and reasoning"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applicant",
            field=models.ForeignKey(
                help_text="Applicant user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="attached_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Portfolio project demonstrating relevant skills",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="profiles.project",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="cover_note",
            field=models.TextField(
                blank=True,
                help_text="Personalized cover letter and motivation",
                max_length=2000,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="job",
            field=models.ForeignKey(
                help_text="Target opportunity",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="opportunities.jobpost",
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="match_score",
            field=models.FloatField(
                default=0.0, help_text="AI compatibility score (0-100)"
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("LINKED", "Linked"),
                    ("VIEWED", "Recruiter Viewed"),
                    ("SHORTLISTED", "Shortlisted"),
                    ("INTERVIEW", "Interview"),
                    ("REJECTED", "Not a Fit"),
                    ("HIRED", "Hired"),
                ],
                default="LINKED",
                help_text="Current application status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="ai_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="AI analysis data, embeddings, and semantic search info",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="applications_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total applications received"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="challenge_description",
            field=models.TextField(
                blank=True,
                help_text="Detailed challenge requirements (e.g., 'Attach a React hooks project')",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Company offering this opportunity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="profiles.company",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="compensation_text",
            field=models.CharField(
                blank=True,
                help_text="Compensation description (e.g., 'Competitive', 'Negotiable')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for visual appeal",
                null=True,
                upload_to="opportunities/covers/",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="deadline_date",
            field=models.DateField(
                blank=True,
                help_text="Specific deadline date for calendar sorting",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="deadline_text",
            field=models.CharField(
                blank=True,
                help_text="Flexible deadline description (e.g., 'Rolling basis', 'ASAP')",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed job description. Markdown supported.",
                verbose_name="The Mission Narrative",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="external_company_logo",
            field=models.ImageField(
                blank=True,
                help_text="Company logo for external postings",
                null=True,
                upload_to="opportunities/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="external_company_name",
            field=models.CharField(
                blank=True,
                help_text="Company name for external postings",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to external application page",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="is_external",
            field=models.BooleanField(
                default=False, help_text="Is this an outside application opportunity?"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="is_official_admin_post",
            field=models.BooleanField(
                default=False, help_text="Mark as official CoreLink platform posting"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="is_open_ended",
            field=models.BooleanField(
                default=True,
                help_text="No specific deadline - always accepting applications",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="is_remote",
            field=models.BooleanField(
                default=False, help_text="Remote work opportunity"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("FULL_TIME", "Full-Time Role"),
                    ("PART_TIME", "Part-Time Role"),
                    ("INTERNSHIP", "Internship"),
                    ("CONTRACT", "Freelance / Contract"),
                    ("GIG", "Gig / Quick Task"),
                    ("CHALLENGE", "Business Challenge"),
                    ("ADVISORY", "Advisory / Mentorship"),
                    ("VOLUNTEER", "Volunteer / Social Impact"),
                    ("COFOUNDER", "Co-Founder"),
                ],
                default="FULL_TIME",
                help_text="Type of opportunity",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STUDENT", "Student / Intern"),
                    ("ENTRY", "Entry Level / Junior"),
                    ("MID", "Mid Level"),
                    ("SENIOR", "Senior Level"),
                    ("LEAD", "Lead / Manager"),
                    ("EXECUTIVE", "Executive / Director"),
                    ("ANY", "Any Level / Not Applicable"),
                ],
                help_text="Required experience level",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="location",
            field=models.CharField(
                blank=True,
                default="Addis Ababa",
                help_text="Job location or 'Remote'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="posted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who posted this opportunity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="Publication timestamp for sorting", null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Required skills for matching",
                related_name="opportunities",
                to="opportunities.skill",
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="requires_challenge",
            field=models.BooleanField(
                default=False, help_text="Require applicants to complete a challenge"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="salary_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum salary (annual or hourly as appropriate)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="salary_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum salary (annual or hourly as appropriate)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO-friendly URL. Auto-generated from title.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="source_name",
            field=models.CharField(
                blank=True,
                help_text="Source platform (e.g., 'Telegram', 'EthioJobs')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending Approval"),
                    ("ACTIVE", "Live"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                help_text="Publication status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="title",
            field=models.CharField(
                help_text="Clear, descriptive job title", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total views for analytics"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="ai_aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="AI synonyms for semantic matching (e.g., ['VueJS', 'Vue.js'])",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Skill category for organization (e.g., 'Engineering', 'Design')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                help_text="Canonical skill name for matching",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="slug",
            field=models.SlugField(
                blank=True, help_text="URL-friendly skill identifier", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["match_score"], name="opportuniti_match_s_5980c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["status", "created_at"], name="opportuniti_status_282862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["is_open_ended"], name="opportuniti_is_open_7e3279_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=models.Index(
                fields=["ai_match_score"], name="opportuniti_ai_matc_a9f3d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="opportuniti_name_d1667b_idx"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["category"], name="opportuniti_categor_cedac9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["is_trending"], name="opportuniti_is_tren_dbc88a_idx"
            ),
        ),
    ]
