# Generated by Django 5.0.2 on 2026-03-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "opportunities",
            "0004_alter_jobapplication_options_alter_jobpost_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="submitter_contact",
            field=models.CharField(
                blank=True,
                help_text="Guest contact info (Telegram handle, Phone, or Email) for admin communication",
                max_length=150,
                null=True,
            ),
        ),
    ]
