# Generated by Django 5.0.2 on 2026-03-01 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessChallenge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Challenge Title')),
                ('description', models.TextField(verbose_name='Challenge Description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SOLVED', 'Solved')], db_index=True, default='OPEN', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='profiles.company')),
            ],
            options={
                'verbose_name': 'Business Challenge',
                'verbose_name_plural': 'Business Challenges',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMessageToAdmin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='The long-form essay of your needs, vision, or challenges.')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted (Pending)'), ('REVIEWING', 'Admin Reviewing'), ('ACTIONING', 'Action in Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='SUBMITTED', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_company_messages', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='profiles.company')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message to Admin',
                'verbose_name_plural': 'Messages to Admin',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyNeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Position Title')),
                ('description', models.TextField(verbose_name='Role Description')),
                ('category', models.CharField(choices=[('FULL_TIME', 'Full-Time Job'), ('PART_TIME', 'Part-Time Job'), ('FREELANCE', 'Freelance / Contract'), ('INTERNSHIP', 'Internship'), ('CO_FOUNDER', 'Co-Founder Role'), ('PROJECT', 'Short-term Project')], db_index=True, max_length=20)),
                ('required_skills', models.CharField(blank=True, help_text='Comma separated', max_length=500, verbose_name='Required Skills')),
                ('arrangement', models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-Site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='profiles.company')),
            ],
            options={
                'verbose_name': 'Company Need',
                'verbose_name_plural': 'Company Needs',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('target_people_description', models.TextField()),
                ('status', models.CharField(choices=[('APPLIED', 'Applied (Pending)'), ('REVIEWING', 'Admin Reviewing'), ('MATCHING', 'Finding Match'), ('CONNECTED', 'Introduction Made'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], db_index=True, default='APPLIED', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_introductions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection Request',
                'verbose_name_plural': 'Connection Requests',
                'ordering': ['-created_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role_title', models.CharField(max_length=150)),
                ('seeking', models.CharField(choices=[('JOB', 'Seeking Professional Job'), ('INTERNSHIP', 'Seeking Internship'), ('BOTH', 'Open to Either')], default='BOTH', max_length=15)),
                ('preferred_location', models.CharField(max_length=255)),
                ('ideal_company_desc', models.TextField()),
                ('value_proposition', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Application Received'), ('VETTING', 'Admin Reviewing Talents'), ('HUNTING', 'Proactively Finding Matches'), ('PLACED', 'Successfully Placed'), ('ARCHIVED', 'Closed / Not Seeking')], default='SUBMITTED', max_length=20)),
                ('admin_match_notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preference Application',
                'verbose_name_plural': 'Preference Applications',
                'ordering': ['-created_at', 'target_role_title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Team Name')),
                ('mission', models.TextField(verbose_name='Mission Statement')),
                ('team_type', models.CharField(choices=[('STARTUP', 'Startup Venture'), ('BUSINESS', 'SME / Business'), ('PROJECT', 'Specific Project'), ('HACK', 'Hackathon Team'), ('LEARNING', 'Learning Group'), ('NON_PROFIT', 'Social Impact')], default='PROJECT', max_length=20)),
                ('roles_needed', models.TextField(blank=True, null=True, verbose_name='Roles Needed')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Group Link')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pending Admin Review'), ('APPROVED', '✅ Active (Public)'), ('REJECTED', '❌ Rejected'), ('ARCHIVED', '📦 Archived')], db_index=True, default='PENDING', max_length=20)),
                ('is_recruiting', models.BooleanField(default=True, verbose_name='Accepting Members')),
                ('admin_feedback', models.TextField(blank=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sender', 'receiver'], name='workspace_c_sender__5add69_idx')],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('narrative', models.TextField(verbose_name='Why do you want to join?')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pending Leader Review'), ('APPROVED', '✅ Accepted'), ('REJECTED', '❌ Declined')], default='PENDING', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='workspace.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('team', 'applicant')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('LEADER', '👑 Leader'), ('MEMBER', '🛠️ Member')], default='MEMBER', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspace.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Membership',
                'ordering': ['-created_at'],
                'unique_together': {('team', 'user')},
            },
        ),
    ]
