# Generated by Django 5.0.2 on 2026-03-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_team_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-generated from name. Must be unique.",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
