# Generated by Django 5.0.2 on 2026-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0004_chatmessage_attachment_chatmessage_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyneed",
            name="company",
        ),
        migrations.AlterField(
            model_name="companymessagetoadmin",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="companymessagetoadmin",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="connectionrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="connectionrequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="joinrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="joinrequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="preferenceapplication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="preferenceapplication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.DeleteModel(
            name="BusinessChallenge",
        ),
        migrations.DeleteModel(
            name="CompanyNeed",
        ),
    ]
