# Generated by Django 5.0.2 on 2026-07-18 06:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0005_remove_companyneed_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='joinrequest',
            name='team',
        ),
        migrations.DeleteModel(
            name='JoinRequest',
        ),
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='assigned_connection',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConnectionRequest',
        ),
        migrations.RemoveField(
            model_name='preferenceapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='PreferenceApplication',
        ),
    ]
