# Generated by Django 5.0.2 on 2026-03-01 20:22

import django.db.models.deletion
import operations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to=operations.models.evidence_file_path)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to=operations.models.evidence_image_path)),
                ('evidence_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', '🟡 Pending Review'), ('VERIFIED', '🟢 Verified'), ('REJECTED', '🔴 Rejected'), ('NEEDS_INFO', '🔵 Needs More Info')], db_index=True, default='PENDING', max_length=20)),
                ('admin_feedback', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Achievement Claim',
                'verbose_name_plural': 'Achievement Claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('telegram_link', models.URLField(max_length=500)),
                ('lead_mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Unit',
                'verbose_name_plural': 'Family Units',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=200)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '⚠️ Security Blackbox',
                'verbose_name_plural': '⚠️ Security Blackbox',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin', 'timestamp'], name='operations__admin_i_304827_idx'), models.Index(fields=['action', 'timestamp'], name='operations__action_e84952_idx')],
            },
        ),
        migrations.CreateModel(
            name='FamilyMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_membership', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='operations.familyunit')),
            ],
            options={
                'verbose_name': 'Family Membership',
                'indexes': [models.Index(fields=['family'], name='operations__family__48f248_idx')],
            },
        ),
    ]
