# Generated by Django 5.0.2 on 2026-03-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementclaim",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="achievementclaim",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="familymembership",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="familymembership",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="familyunit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="familyunit",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
    ]
