# Generated by Django 5.0.2 on 2026-03-01 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('PLATFORM', 'Platform Update'), ('EVENT', 'Community Event'), ('INSIGHT', 'Market Insight'), ('SPOTLIGHT', 'Member Spotlight')], default='PLATFORM', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='content/news_covers/')),
                ('summary', models.TextField(help_text='Short teaser for the grid card.', max_length=300)),
                ('body', models.TextField(help_text='Full content. Supports HTML/Markdown.')),
                ('author_name', models.CharField(default='CoreLink Team', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('read_time', models.IntegerField(default=5, help_text='Minutes to read')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='content/news_gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.newsarticle')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NexusArticle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NexusGalleryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='public/nexus/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('nexus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.nexusarticle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
