# Generated by Django 5.0.2 on 2026-03-15 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsgalleryimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="nexusarticle",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Nexus Article",
                "verbose_name_plural": "Nexus Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="nexusgalleryimage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Nexus Gallery Image",
                "verbose_name_plural": "Nexus Gallery Images",
            },
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="author_name",
            field=models.CharField(
                default="CoreLink Team",
                help_text="Display name for the content author",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="body",
            field=models.TextField(
                help_text="Full content. Supports HTML and Markdown formatting"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("PLATFORM", "Platform Update"),
                    ("EVENT", "Community Event"),
                    ("INSIGHT", "Market Insight"),
                    ("SPOTLIGHT", "Member Spotlight"),
                ],
                default="PLATFORM",
                help_text="Content category for organization and filtering",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Primary cover image. Auto-optimized for web.",
                null=True,
                upload_to="content/news_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="is_published",
            field=models.BooleanField(
                default=True, help_text="Controls visibility on the platform"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="read_time",
            field=models.IntegerField(
                default=5, help_text="Estimated reading time in minutes"
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="SEO-friendly URL. Auto-generated from title.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="summary",
            field=models.TextField(
                help_text="Short teaser for the grid card and previews", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(
                help_text="Headline for the news article", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="article",
            field=models.ForeignKey(
                help_text="Parent news article",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="content.newsarticle",
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="caption",
            field=models.CharField(
                blank=True, help_text="Optional caption for the image", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="image",
            field=models.ImageField(
                help_text="Gallery image. Auto-optimized for web.",
                upload_to="content/news_gallery/",
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Display order in the gallery"
            ),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="author",
            field=models.ForeignKey(
                help_text="Content author",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nexus_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="content",
            field=models.TextField(
                help_text="Full article content. Supports HTML and Markdown"
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Controls visibility in the knowledge base"
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="title",
            field=models.CharField(
                help_text="Article title for the knowledge base", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="nexusarticle",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="nexusgalleryimage",
            name="caption",
            field=models.CharField(
                blank=True,
                help_text="Descriptive caption for the image",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="nexusgalleryimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when the record was created"
            ),
        ),
        migrations.AlterField(
            model_name="nexusgalleryimage",
            name="image",
            field=models.ImageField(
                help_text="Article image or diagram", upload_to="public/nexus/"
            ),
        ),
        migrations.AlterField(
            model_name="nexusgalleryimage",
            name="nexus",
            field=models.ForeignKey(
                help_text="Parent Nexus article",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery",
                to="content.nexusarticle",
            ),
        ),
        migrations.AlterField(
            model_name="nexusgalleryimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when the record was last updated"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["category", "is_published"],
                name="content_new_categor_82e3ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(
                fields=["created_at"], name="content_new_created_6e17c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsarticle",
            index=models.Index(fields=["slug"], name="content_new_slug_7b4d73_idx"),
        ),
        migrations.AddIndex(
            model_name="newsgalleryimage",
            index=models.Index(
                fields=["article", "order"], name="content_new_article_9ea3d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexusarticle",
            index=models.Index(
                fields=["author", "is_published"], name="content_nex_author__f595ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexusarticle",
            index=models.Index(
                fields=["created_at"], name="content_nex_created_38fc10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nexusgalleryimage",
            index=models.Index(
                fields=["nexus", "created_at"], name="content_nex_nexus_i_692eb7_idx"
            ),
        ),
    ]
